var Data = [
  {
    id: 1,
    ho: null,
    tenDem: null,
    ten: "admin",
    phapDanh: "Admin",
    anhChup: "",
    soDienThoai: "0942825665",
    email: "admin@gmail.com",
    ngaySinh: null,
    ngayXuatGia: null,
    daHoanTuc: null,
    ngayHoanTuc: null,
    gioiTinh: null,
    ngayCapNhat: null,
    chua: null,
    kieuThanhVien: {
      id: 1,
      code: "1",
      tenKieu: "admin",
    },
    phatTuDaoTrangListpt: [],
    truTriChuaList: [],
  },
  {
    id: 2,
    ho: "Hor",
    tenDem: "yu",
    ten: "1",
    phapDanh: "HuyenM1",
    anhChup: "",
    soDienThoai: "0341111111",
    email: "yu1@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: false,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 1,
      tenChua: "Chùa 1",
      ngayThanhLap: "2018-01-01T00:00:00",
      diaChi: "Địa chỉ 1",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [
      {
        id: 1,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 2,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 3,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
    ],
    truTriChuaList: [
      {
        id: 1,
        tenChua: "Chùa 1",
        ngayThanhLap: "2018-01-01T00:00:00",
        diaChi: "Địa chỉ 1",
        capNhat: "2018-01-01T00:00:00",
      },
    ],
  },
  {
    id: 3,
    ho: "Hor",
    tenDem: "yu",
    ten: "2",
    phapDanh: "HuyenM2",
    anhChup: "/anh2",
    soDienThoai: "341111112",
    email: "yu2@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: false,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 2,
      tenChua: "Chùa 2",
      ngayThanhLap: "2019-01-01T00:00:00",
      diaChi: "Địa chỉ 2",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [
      {
        id: 4,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 5,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 6,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
    ],
    truTriChuaList: [
      {
        id: 2,
        tenChua: "Chùa 2",
        ngayThanhLap: "2019-01-01T00:00:00",
        diaChi: "Địa chỉ 2",
        capNhat: "2018-01-01T00:00:00",
      },
    ],
  },
  {
    id: 4,
    ho: "Hor",
    tenDem: "yu",
    ten: "3",
    phapDanh: "HuyenM3",
    anhChup: "/anh3",
    soDienThoai: "341111113",
    email: "yu3@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: false,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 3,
      tenChua: "Chùa 3",
      ngayThanhLap: "2020-01-01T00:00:00",
      diaChi: "Địa chỉ 3",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [
      {
        id: 7,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 8,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 9,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
    ],
    truTriChuaList: [
      {
        id: 3,
        tenChua: "Chùa 3",
        ngayThanhLap: "2020-01-01T00:00:00",
        diaChi: "Địa chỉ 3",
        capNhat: "2018-01-01T00:00:00",
      },
    ],
  },
  {
    id: 5,
    ho: "Hor",
    tenDem: "yu",
    ten: "4",
    phapDanh: "HuyenM4",
    anhChup: "/anh4",
    soDienThoai: "341111114",
    email: "yu4@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: false,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 1,
      tenChua: "Chùa 1",
      ngayThanhLap: "2018-01-01T00:00:00",
      diaChi: "Địa chỉ 1",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [
      {
        id: 10,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 11,
        daThamGia: false,
        lyDoKhongThamGia: "Lý do 1",
      },
      {
        id: 12,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
    ],
    truTriChuaList: [],
  },
  {
    id: 6,
    ho: "Hor",
    tenDem: "yu",
    ten: "5",
    phapDanh: "HuyenM5",
    anhChup: "/anh5",
    soDienThoai: "341111115",
    email: "yu5@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: false,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 2,
      tenChua: "Chùa 2",
      ngayThanhLap: "2019-01-01T00:00:00",
      diaChi: "Địa chỉ 2",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [
      {
        id: 13,
        daThamGia: false,
        lyDoKhongThamGia: "Lý do 1",
      },
      {
        id: 14,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
      {
        id: 15,
        daThamGia: true,
        lyDoKhongThamGia: null,
      },
    ],
    truTriChuaList: [],
  },
  {
    id: 7,
    ho: "Hor",
    tenDem: "yu",
    ten: "6",
    phapDanh: "HuyenM6",
    anhChup: "/anh6",
    soDienThoai: "341111116",
    email: "yu6@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: false,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 3,
      tenChua: "Chùa 3",
      ngayThanhLap: "2020-01-01T00:00:00",
      diaChi: "Địa chỉ 3",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [
      {
        id: 16,
        daThamGia: false,
        lyDoKhongThamGia: "Lý do 1",
      },
      {
        id: 17,
        daThamGia: false,
        lyDoKhongThamGia: "Lý do 2",
      },
      {
        id: 18,
        daThamGia: false,
        lyDoKhongThamGia: "Lý do 3",
      },
    ],
    truTriChuaList: [],
  },
  {
    id: 8,
    ho: "Hor",
    tenDem: "yud",
    ten: "ha",
    phapDanh: "HuyenM5",
    anhChup: "/anh7",
    soDienThoai: "341111117",
    email: "yu7@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: true,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 2,
      tenChua: "Chùa 2",
      ngayThanhLap: "2019-01-01T00:00:00",
      diaChi: "Địa chỉ 2",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [],
    truTriChuaList: [],
  },
  {
    id: 9,
    ho: "Hord",
    tenDem: "yu",
    ten: "ha",
    phapDanh: "HuyenM5",
    anhChup: "/anh8",
    soDienThoai: "341111118",
    email: "yu8@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: true,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 2,
      tenChua: "Chùa 2",
      ngayThanhLap: "2019-01-01T00:00:00",
      diaChi: "Địa chỉ 2",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [],
    truTriChuaList: [],
  },
  {
    id: 10,
    ho: "Horq",
    tenDem: "yu",
    ten: "ha",
    phapDanh: "HuyenM5",
    anhChup: "/anh9",
    soDienThoai: "341111119",
    email: "yu9@gmail.com",
    ngaySinh: "1981-01-01",
    ngayXuatGia: "1999-01-01",
    daHoanTuc: true,
    ngayHoanTuc: null,
    gioiTinh: 1,
    ngayCapNhat: "2018-01-01T00:00:00",
    chua: {
      id: 2,
      tenChua: "Chùa 2",
      ngayThanhLap: "2019-01-01T00:00:00",
      diaChi: "Địa chỉ 2",
      capNhat: "2018-01-01T00:00:00",
    },
    kieuThanhVien: {
      id: 2,
      code: "2",
      tenKieu: "Phật Tử",
    },
    phatTuDaoTrangListpt: [],
    truTriChuaList: [],
  },
];
export default Data;
